language: cpp

sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode11.4

script:
  - uname -a ; sw_vers ; $CXX --version
  - brew audit ./credz.rb
  - brew install ./credz.rb
  - brew test ./credz.rb
