language: cpp

sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode11.4

before_install:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - brew update
  - brew tap ryangraham/credz git@github.com:ryangraham/homebrew-credz

script:
  - uname -a ; sw_vers ; $CXX --version
  - brew audit credz
  - brew install credz
  - brew test credz
